services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    
    volumes:
      - ./:/app
      
    working_dir: /app
    
    ports:
      - "8080:8080"
      
    environment:
      XDEBUG_MODE: "off"
      XDEBUG_CONFIG: "client_host=host.internal"
      
    command: ["tail", "-f", "/dev/null"]