#!/usr/bin/env php
<?php

// CLI実行ファイル

require __DIR__ . '/vendor/autoload.php';

use CLI\NewCommand;
use CLI\BuildCommand;
use CLI\ServeCommand;
use CLI\DeployCommand;

$args = $argv;
array_shift($args);

$command = $args[0] ?? null;

switch ($command) {
    case 'new':
        $title = $args[1] ?? 'untitled';
        (new NewCommand())->execute($title);
        break;
    // case 'build':
    //     (new BuildCommand())->execute();
    //     break;
    case 'serve':
        $port = $args[1] ?? 8080;
        (new ServeCommand())->execute((int)$port);
        break;
    // case 'deploy':
    //     (new DeployCommand())->execute();
    //     break;
    default:
        echo "Usage: markblog [new | build | serve | deploy] [options]\n";
        break;
}