#!/usr/bin/env php
<?php

declare(strict_types=1);

use Symfony\Component\Console\Application;
use CLI\NewCommand;
use CLI\BuildCommand;
use CLI\ServeCommand;
use CLI\DeployCommand;

require_once __DIR__ . '/vendor/autoload.php';

$application = new Application('MarkBlog CLI', '0.1.0');

// コマンド登録
$application->add(new NewCommand());
$application->add(new BuildCommand());
$application->add(new ServeCommand());
// $application->add(new DeployCommand());

// Symfony Console が自動で $argv を処理
$application->run();
